[package]
name = "elmlog"
version = "2.13.0-alpha"
edition = "2021"

[dependencies]
bincode = "1.3.3"
crossterm = "0.28.1"
dirs = "5.0.1"
fs2 = "0.4.3"
once_cell = "1.20.2"
ratatui = "0.29.0"
serde = { version = "1.0.213", features = ["derive"] }
