[package]
name = "sieve-selector"
version = "2.1.0-alpha"
edition = "2021"

[dependencies]
bincode = "1.3.3"
crossterm = "0.28.1"
dirs = "5.0.1"
fs2 = "0.4.3"
ratatui = "0.28.1"
serde = { version = "1.0.213", features = ["derive"] }
